FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
CMD python mysite/manage.py migrate \
  && python mysite/manage.py loaddata data.json \
  && python mysite/manage.py runserver 0:8080